### ISSUE TITLE
This repository's name should have .jl

### ISSUE THREAD

**Issue by p1scescom** [abap34/ac-library-jl#19]
Normally, Julia package's repositorys have .jl in the repository'name.
I reccomend to rename this reposity .jl.
ex. ACL.jl AtCoderLibrary.jl
(Maybe it's not good to use directly company name)

**Comment by abap34** [comment]
ありがとうございます。
どちらかというとコード集的な性質のものになるかと思い作成したのですが、将来的なことを考えたらそちらの方が良さそうですね。
ACL.jlに変更します。
参考:https://twitter.com/chokudai/status/1303025509488496645?s=21
